image: Ubuntu1804  # образ для сборки

stack: node 12  # окружение

branches:
  only:
    - master  # ветка git

cache: node_modules  # кеширование

install:
  - sudo apt-get install -y xvfb
  - sudo apt-get -y install xorg xvfb gtk2-engines-pixbuf
  - sudo apt-get -y install dbus-x11 xfonts-base xfonts-100dpi xfonts-75dpi xfonts-cyrillic xfonts-scalable
  - npm install  # команда установки зависимостей

build: off  # отключаем встроенную в appveyor систему сборки

build_script:
  - npm run build   # команда сборки

test_script:
  - npm run lint && npm run test # скрипт тестирования

deploy_script: #скрипт развёртывания 
  - git config --global credential.helper store
  - git config --global user.name AppVeyor 
  - git config --global user.email ci@appveyor.com 
  - echo "https://$GITHUB_TOKEN:x-oauth-basic@github.com" > "$HOME/.git-credentials"
  - npx push-dir --dir=dist --branch=gh-pages --force --verbose